highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'

plugins: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

url: https://unifreak.github.io/
name: unifreak
title: UniFreak | Another yet unique freak is showing a freakshow
description: "Fanghao's personal weblog, on coding or such stuff"

my:
    displayName: UniFreak
    realName: FangHao
    realName_cn: 方浩
    jobTitle: "PHP Coder"
    contact:
        qq: 744910240
        email: fanghao90s@gmail.com
        github: http://www.github.com/UniFreak
        qzone: http://744910240.qzone.qq.com
        pinterest: https://www.pinterest.com/miblah/
        tel: 153 6999 7084
        address:
            country: China
            state: Beijing
            city: Beijing
            distribute: ChaoYang
            postcode: 000000
            cell: "Wangxin Garden"
    skills:
        frontend: ["HTML | Markdown", "CSS | SASS", "JS | jQuery", "Bootstrap"]
        backend: ["PHP", "Python", "Shell", MySQL", "Redis", "Regex", "Laravel", "Lumen"]
        tools: ["Sublime Text", "Git | Github", "Linux", "Jekyll | Liquid"]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
