highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'

plugins:
  - jekyll-paginate
paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

url: https://unifreak.github.io/
name: unifreak
title: unifreak | another yet unique freak is showing a freakshow
shout:
  - on the way to death
  - on the way of learning
description: "Fanghao's personal weblog, on coding or such stuff"

collections:
  book_reviews:
    output: true

my:
  displayName: UniFreak
  realName: FangHao
  realName_cn: 方浩
  jobTitle: "PHP Coder"
  contact:
    qq: 744910240
    email: fanghao90s@gmail.com
    github: http://www.github.com/UniFreak
    qzone: http://744910240.qzone.qq.com
    pinterest: https://www.pinterest.com/miblah/
    tel: 153 6999 7084
    address:
      country: China
      state: Beijing
      city: Beijing
      distribute: ChaoYang
      postcode: 000000
      cell: "Wangxin Garden"
  skills:
    frontend: ["HTML | Markdown", "CSS | SASS", "JS | jQuery", "Bootstrap"]
    backend: ["PHP", "Python", "Shell", MySQL", "Redis", "Regex", "Laravel", "Lumen"]
    tools: ["Sublime Text", "Git | Github", "Linux", "Jekyll | Liquid"]

