highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

url: https://unifreak.github.io/
name: unifreak
title: unifreak | another yet unique freak is showing a freakshow
shout:
  - on the way to death
  - on the way of learning
description: "Fanghao's personal weblog, on coding or such stuff"

disqus:
  shortname: 'unifreak'
  comments: true

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-154982899-1      # Required - replace with your tracking id

collections:
  book_reviews:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"